### ISSUE TITLE
🤷‍♂️ 请问你们的代码有测试过吗？一大堆问题😤

### ISSUE THREAD

**Issue by geekyouth** [aliyun/MaxCompute-Spark#3]
解决步骤：

1-  注释掉所有scope 标签；
2- 添加依赖：
```
<!-- https://mvnrepository.com/artifact/org.scala-lang.modules/scala-xml -->
<dependency>
    <groupId>org.scala-lang.modules</groupId>
    <artifactId>scala-xml_2.11</artifactId>
    <version>1.0.5</version>
</dependency>
```
3-  .master("local[*]")

否则你有处理不完的错误。。。。🤔

![image](https://user-images.githubusercontent.com/12899262/78987850-c8da1100-7b61-11ea-9be4-c050c214ff5d.png)

![image](https://user-images.githubusercontent.com/12899262/78987848-c7104d80-7b61-11ea-836f-fa45b2550260.png)

![image](https://user-images.githubusercontent.com/12899262/78987842-c4adf380-7b61-11ea-96c8-fc686d054da1.png)

**Comment by cornmonster** [comment]
https://github.com/aliyun/MaxCompute-Spark/wiki/02.-%E6%90%AD%E5%BB%BA%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83

IDE里面运行需要配置运行环境，具体参考文档
